Repository workflix/workflix-full, pull requests merged in 2024-05, with the labels that each got.

#71 [ADD] estilos home
  frontend/web/3.0.00/src/app/pages/home/home.component.css
Labels: Migration

#77 Puerto angular back
  backend/spring/src/main/java/com/tec/workflix/controllers/LoginApiController.java
  backend/spring/src/main/java/com/tec/workflix/controllers/RegisterApiController.java
  backend/spring/src/main/java/com/tec/workflix/controllers/ServicioController.java
Labels: enhancement

#81 [FIX] organizacion rutas - vinculacion con guards
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/guards/auth.guard.ts
Labels: bug

#83 Registrarse page
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.css
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.html
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.spec.ts
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.ts
Labels: Migration

#84 Migration tarjetas
  frontend/web/3.0.00/src/app/app.component.ts
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/home/home.component.html
  frontend/web/3.0.00/src/app/pages/home/home.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.css
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.spec.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/assets/images/foto_mujer.jpg
  frontend/web/3.0.00/src/assets/images/profesional-1.jpg
  frontend/web/3.0.00/src/assets/images/profesional-2.jpg
  frontend/web/3.0.00/src/assets/images/profesional-3.jpg
Labels: Migration

#87 Migration quienes somos
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.ts
  frontend/web/3.0.00/src/app/pages/quienes-somos/quienes-somos.component.css
  frontend/web/3.0.00/src/app/pages/quienes-somos/quienes-somos.component.html
  frontend/web/3.0.00/src/app/pages/quienes-somos/quienes-somos.component.spec.ts
  frontend/web/3.0.00/src/app/pages/quienes-somos/quienes-somos.component.ts
  frontend/web/3.0.00/src/assets/images/Grupo_trabajo.png
Labels: enhancement

#88 [ADD] migracion footer
  frontend/web/3.0.00/src/app/components/footer/footer.component.html
Labels: enhancement

#89 Migration perfil pages
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.css
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.spec.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
Labels: enhancement

#90 Funcionalidad nav-bar
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.ts
Labels: enhancement

#91 Funcionalidad tarjetas
  frontend/web/3.0.00/src/app/pages/home/home.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: enhancement

#92 [DEL] nombre de usuario de prueba
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
Labels: bug

#93 Cambios de estilo del ingreso. (incompleto )
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.css
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.html
Labels: Diseño UX/UI

#95 Se corrige estilo de formulario de ingreso.
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.css
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.html
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.ts
Labels: enhancement

#97 Migración Recupero de Clave
  frontend/web/3.0.00/src/app/app.component.ts
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.html
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.ts
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.css
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.html
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.spec.ts
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.ts
  frontend/web/3.0.00/src/app/pages/register/archivo_vacio.txt
Labels: Migration

#100 Crear las cards de team workflix
  frontend/web/3.0.00/src/app/pages/quienes-somos/quienes-somos.component.css
  frontend/web/3.0.00/src/app/pages/quienes-somos/quienes-somos.component.html
Labels: enhancement

#106 Se agrega componente terminos, para ver en registro, se agrega material
  frontend/web/3.0.00/angular.json
  frontend/web/3.0.00/package-lock.json
  frontend/web/3.0.00/package.json
  frontend/web/3.0.00/src/app/app.component.ts
  frontend/web/3.0.00/src/app/app.config.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.css
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.css
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.html
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.ts
  frontend/web/3.0.00/src/app/pages/terminos/terminos.component.css
  frontend/web/3.0.00/src/app/pages/terminos/terminos.component.html
  frontend/web/3.0.00/src/app/pages/terminos/terminos.component.spec.ts
  frontend/web/3.0.00/src/app/pages/terminos/terminos.component.ts
  frontend/web/3.0.00/src/index.html
  frontend/web/3.0.00/src/styles.css
Labels: Diseño UX/UI

#107 Fix
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.ts
  frontend/web/3.0.00/src/app/guards/auth.guard.ts
  frontend/web/3.0.00/src/app/services/login.service.ts
Labels: enhancement

#108 User service
  backend/spring/src/main/java/com/tec/workflix/controllers/UsuarioServicioController.java
  backend/spring/src/main/java/com/tec/workflix/interfaces/IUsuarioServicioInterface.java
  backend/spring/src/main/java/com/tec/workflix/models/UsuarioServicio.java
  backend/spring/src/main/java/com/tec/workflix/modelsDAO/UsuarioServicioDAO.java
  backend/spring/src/main/java/com/tec/workflix/services/UsuarioServicioService.java
  frontend/web/2.0.23/src/app/pages/perfil-usuario/perfil-usuario.component.css
Labels: enhancement

#109 Migration preguntas frecuentes
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/footer/footer.component.html
Labels: enhancement

#110 Estilos formularios
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/contacto/contacto.component.css
  frontend/web/3.0.00/src/app/pages/contacto/contacto.component.html
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.css
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.html
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.css
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.html
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.ts
Labels: enhancement

#113 Dashboard, tabla de clientes y profesionales en modulo independiente
  frontend/web/3.0.00/angular.json
  frontend/web/3.0.00/package-lock.json
  frontend/web/3.0.00/package.json
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.css
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.spec.ts
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.ts
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.module.ts
  frontend/web/3.0.00/src/assets/css/materialdesignicons.min.css
  frontend/web/3.0.00/src/assets/css/style.css
  frontend/web/3.0.00/src/assets/css/vendor.bundle.base.css
  frontend/web/3.0.00/src/assets/images/circle.svg
  frontend/web/3.0.00/src/assets/js/Chart.min.js
  frontend/web/3.0.00/src/assets/js/dashboard.js
  frontend/web/3.0.00/src/assets/js/hoverable-collapse.js
  frontend/web/3.0.00/src/assets/js/jquery.cookie.js
  frontend/web/3.0.00/src/assets/js/misc.js
  frontend/web/3.0.00/src/assets/js/off-canvas.js
  frontend/web/3.0.00/src/assets/js/todolist.js
  frontend/web/3.0.00/src/assets/js/vendor.bundle.base.js
  frontend/web/3.0.00/src/index.html
Labels: Migration

#114 Funcionalidad barra búsqueda
  backend/spring/src/main/resources/application.properties
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.ts
  frontend/web/3.0.00/src/app/pages/busqueda-profesional/busqueda-profesional.component.css
  frontend/web/3.0.00/src/app/pages/busqueda-profesional/busqueda-profesional.component.html
  frontend/web/3.0.00/src/app/pages/busqueda-profesional/busqueda-profesional.component.spec.ts
  frontend/web/3.0.00/src/app/pages/busqueda-profesional/busqueda-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/services/user.service.ts
Labels: enhancement

#115 conflicto ramas
  frontend/web/3.0.00/src/app/app.routes.ts
Labels: bug

#116 Valoracion Perfil
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.css
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.html
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.spec.ts
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.ts
  frontend/web/3.0.00/src/assets/images/valoracion_workflix.png
Labels: enhancement

#117 Funcionalidad perfil
  backend/spring/src/main/resources/application.properties
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.css
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.html
  frontend/web/3.0.00/src/app/pages/terminos/terminos.component.css
  frontend/web/3.0.00/src/app/pages/terminos/terminos.component.html
Labels: enhancement

#119 Ordenamiento de carpetas y componentes
  frontend/web/3.0.00/angular.json
  frontend/web/3.0.00/package-lock.json
  frontend/web/3.0.00/package.json
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.css
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.spec.ts
  frontend/web/3.0.00/src/app/pages/dashboard/admin/admin.component.ts
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.module.ts
  frontend/web/3.0.00/src/assets/css/materialdesignicons.min.css
  frontend/web/3.0.00/src/assets/css/style.css
  frontend/web/3.0.00/src/assets/css/vendor.bundle.base.css
  frontend/web/3.0.00/src/assets/images/circle.svg
  frontend/web/3.0.00/src/assets/js/Chart.min.js
  frontend/web/3.0.00/src/assets/js/dashboard.js
  frontend/web/3.0.00/src/assets/js/hoverable-collapse.js
  frontend/web/3.0.00/src/assets/js/jquery.cookie.js
  frontend/web/3.0.00/src/assets/js/misc.js
  frontend/web/3.0.00/src/assets/js/off-canvas.js
  frontend/web/3.0.00/src/assets/js/todolist.js
  frontend/web/3.0.00/src/assets/js/vendor.bundle.base.js
  frontend/web/3.0.00/src/index.html
Labels: bug

#120 Dashboard back front
  backend/spring/src/main/java/com/tec/workflix/configuration/CorsConfig.java
  backend/spring/src/main/java/com/tec/workflix/controllers/UsuarioController.java
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.css
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.spec.ts
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.ts
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.css
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.spec.ts
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
  frontend/web/3.0.00/src/app/services/user.service.ts
Labels: enhancement

#121 Privilegios
  backend/spring/src/main/java/com/tec/workflix/models/Usuario.java
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/guards/auth.guard.ts
  frontend/web/3.0.00/src/app/models/user.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.ts
  frontend/web/3.0.00/src/app/services/login.service.ts
Labels: enhancement

#126 Footer site page
  frontend/web/3.0.00/src/app/pages/site/footer-site/footer-site.component.css
  frontend/web/3.0.00/src/app/pages/site/footer-site/footer-site.component.html
Labels: enhancement

#127 Frontend site
  frontend/web/3.0.00/src/app/pages/site/site.component.css
  frontend/web/3.0.00/src/app/pages/site/site.component.html
  frontend/web/3.0.00/src/assets/images/13.png
Labels: enhancement

#128 Carrito
  backend/spring/src/main/java/com/tec/workflix/models/Usuario.java
  frontend/web/3.0.00/src/app/app.component.html
  frontend/web/3.0.00/src/app/app.component.ts
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.css
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.html
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.spec.ts
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.css
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.ts
  frontend/web/3.0.00/src/app/models/user.ts
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/services/carrito.service.spec.ts
  frontend/web/3.0.00/src/app/services/carrito.service.ts
  frontend/web/3.0.00/src/assets/images/servicio_adquirido.png
Labels: bug, enhancement

#131 agregando quienes somos
  frontend/web/3.0.00/src/app/pages/site/site.component.html
  frontend/web/3.0.00/src/app/pages/site/site.component.ts
Labels: enhancement

#132 Funcionalidad ver detalle
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.css
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.css
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.html
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.ts
Labels: enhancement

#133 Frontend site
  frontend/web/3.0.00/src/app/pages/site/site.component.css
  frontend/web/3.0.00/src/app/pages/site/site.component.html
Labels: enhancement

#134 Crear perfil profesional
  backend/spring/src/main/java/com/tec/workflix/configuration/CorsConfig.java
  backend/spring/src/main/java/com/tec/workflix/modelsDAO/UsuarioDAO.java
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.css
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.html
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.spec.ts
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.css
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.ts
  frontend/web/3.0.00/src/app/services/user.service.ts
Labels: bug, enhancement

#136 Agregar funcionalidad perfilusu
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.css
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.css
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.css
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.css
Labels: enhancement

#138 Aplicando mejoras en el dashboard
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.css
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.css
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.html
Labels: enhancement

#139 Footer site page
  frontend/web/3.0.00/src/app/pages/site/footer-site/footer-site.component.css
  frontend/web/3.0.00/src/app/pages/site/footer-site/footer-site.component.html
Labels: enhancement

#143 IEEE actualizado
  documentos/IEEE830_Workflix_2024.pdf
Labels: documentation

#164 Error CRUD de servicios no funcional
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/models/service.ts
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.css
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.spec.ts
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.ts
  frontend/web/3.0.00/src/app/services/service.service.spec.ts
  frontend/web/3.0.00/src/app/services/service.service.ts
Labels: enhancement

#165 Filtrar cards profesionales por usuario profesional
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.ts
  frontend/web/3.0.00/src/app/models/user.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/services/user.service.ts
Labels: bug, enhancement

#166 [ADD] filtro usuario profesional null precio
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: bug, enhancement

#170 [FIX] bug dashboard por tipo ok
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.html
Labels: bug

#171 Eliminar cuenta usuario
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.css
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.html
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.css
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
Labels: enhancement

#172 Pasarela de pago
  frontend/web/3.0.00/package-lock.json
  frontend/web/3.0.00/package.json
  frontend/web/3.0.00/server_pasarela/.gitignore
  frontend/web/3.0.00/server_pasarela/README.md
  frontend/web/3.0.00/server_pasarela/package-lock.json
  frontend/web/3.0.00/server_pasarela/package.json
  frontend/web/3.0.00/server_pasarela/public/cancel.html
  frontend/web/3.0.00/server_pasarela/public/checkout.html
  frontend/web/3.0.00/server_pasarela/public/checkout.js
  frontend/web/3.0.00/server_pasarela/public/return.html
  frontend/web/3.0.00/server_pasarela/public/return.js
  frontend/web/3.0.00/server_pasarela/public/style.css
  frontend/web/3.0.00/server_pasarela/public/success.html
  frontend/web/3.0.00/server_pasarela/server.js
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.html
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.ts
  frontend/web/3.0.00/src/app/envs/environment.ts
  frontend/web/3.0.00/src/app/services/checkout.service.spec.ts
  frontend/web/3.0.00/src/app/services/checkout.service.ts
  frontend/web/3.0.00/src/index.html
Labels: enhancement

#173 Bug boton
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: bug

#175 [FIX] En la vista del dashboard se agrega columna con Correo y en use…
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.ts
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.ts
Labels: bug

#176 Fix
  backend/spring/src/main/java/com/tec/workflix/models/Usuario.java
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.ts
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.css
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.html
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.spec.ts
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.css
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.html
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.html
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/pages/valoracion-perfil/valoracion-perfil.component.spec.ts
Labels: bug

#178 Fix perfil usuario
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.html
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
Labels: bug, enhancement

#195 112 botones pill filtros
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.css
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/index.html
Labels: bug

#196 Fix mobile
  frontend/mobile/workflix/.idea/deploymentTargetDropDown.xml
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/catalogo/CatalogoActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardAdminVistaActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard_admin/DashboardUsuariosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil_terminos/PerfilTerminosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
Labels: enhancement

#197 Env
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/Environment.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/login/LoginActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/register/RegisterActivity.java
Labels: bug

#202 [FIX] re estructura general proyecto mobile
  frontend/mobile/workflix/app/src/main/AndroidManifest.xml
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/adapters/ServicioActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/adapters/UsuarioActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/LoggedInUserView.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/LoginActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/LoginFormState.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/LoginResult.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/LoginViewModel.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/LoginViewModelFactory.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/register/RegisterActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardAdminActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardAdminVistaActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardServiciosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardUsuariosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/HomeFragment.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/eliminar_cuenta/EliminarCuentaActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/perfil_terminos/PerfilTerminosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/perfil_terminos/terminosCondiciones.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/restablecer/RestablecerActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/tarjetas/CatalogoActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/tarjetas/CatalogoAdapter.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/tarjetas/TarjetaAmpliadaActivity.java
  frontend/mobile/workflix/app/src/main/res/layout-w1240dp/activity_login.xml
  frontend/mobile/workflix/app/src/main/res/layout-w936dp/activity_login.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_catalogo.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_dashboard_admin_vista.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_dashboard_servicios.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_eliminar_cuenta.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_listar_administradores.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_listar_servicios.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_listar_usuarios.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_login.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_perfil_terminos.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_register.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_tarjeta_ampliada.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_terminos_condiciones.xml
  frontend/mobile/workflix/app/src/main/res/layout/content_listar.xml
  frontend/mobile/workflix/app/src/main/res/layout/content_listar_administradores.xml
  frontend/mobile/workflix/app/src/main/res/layout/content_listar_servicios.xml
  frontend/mobile/workflix/app/src/main/res/layout/dashboard_admin.xml
  frontend/mobile/workflix/app/src/main/res/layout/dashboard_usuarios.xml
  frontend/mobile/workflix/app/src/main/res/menu/menu_main.xml
Labels: bug

#203 Func tarjeta ampliada
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.css
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.html
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/services/selected-user.service.spec.ts
  frontend/web/3.0.00/src/app/services/selected-user.service.ts
Labels: enhancement

#204 168 agregar en cliente ofrecerse como profesional
  backend/spring/src/main/java/com/tec/workflix/modelsDAO/UsuarioDAO.java
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.css
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
Labels: enhancement

#207 Page not found
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/page-not-found/page-not-found.component.css
  frontend/web/3.0.00/src/app/pages/page-not-found/page-not-found.component.html
  frontend/web/3.0.00/src/app/pages/page-not-found/page-not-found.component.spec.ts
  frontend/web/3.0.00/src/app/pages/page-not-found/page-not-found.component.ts
  frontend/web/3.0.00/src/assets/images/not_found_page.png
Labels: bug, enhancement

#210 Boton ir a web
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  frontend/mobile/workflix/app/src/main/res/drawable/workflix_web_vector.xml
  frontend/mobile/workflix/app/src/main/res/menu/nav_menu.xml
Labels: enhancement

#212 211 tk131 bug perfil profesional
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
Labels: bug

#215 Bug perfil-usuario and perfil-profesional
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.css
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.html
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.css
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
Labels: bug

#217 Diseño UI site
  documentos/Site Mobil.jpg
  documentos/Site Page Tablet.jpg
  documentos/Site Page Web.jpg
Labels: Diseño UX/UI

#220 Bugs varios
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/advertencia/advertencia.component.css
  frontend/web/3.0.00/src/app/pages/advertencia/advertencia.component.html
  frontend/web/3.0.00/src/app/pages/advertencia/advertencia.component.spec.ts
  frontend/web/3.0.00/src/app/pages/advertencia/advertencia.component.ts
  frontend/web/3.0.00/src/app/pages/destacados/destacados.component.css
  frontend/web/3.0.00/src/app/pages/destacados/destacados.component.html
  frontend/web/3.0.00/src/app/pages/destacados/destacados.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.css
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/assets/images/advertencia.png
Labels: bug

#221 Responsive navbar
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.html
  frontend/web/3.0.00/src/app/components/nav-bar/nav-bar.component.ts
Labels: bug

#222 Service services dashboard
  backend/spring/src/main/java/com/tec/workflix/controllers/ServicioController.java
  backend/spring/src/main/java/com/tec/workflix/controllers/UsuarioServicioController.java
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.ts
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.ts
  frontend/web/3.0.00/src/app/services/service.service.ts
Labels: enhancement

#224 Fix - Messages - Alert - Methods - Dashboard
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/dashboard.component.ts
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/service-create/service-create.component.ts
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.html
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.ts
Labels: bug

#226 ADD serviceService to profession
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/services/service.service.ts
Labels: enhancement

#227 [FIX] resolving theme conflicts
  frontend/mobile/workflix/app/src/main/res/values/themes.xml
Labels: bug

#228 [ADD] Whatsapp contact button on professional expanded card
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/tarjetas/TarjetaAmpliadaActivity.java
  frontend/mobile/workflix/app/src/main/res/drawable/baseline_whatsapp_24.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_tarjeta_ampliada.xml
Labels: enhancement

#229 Services users
  backend/spring/src/main/java/com/tec/workflix/models/Servicio.java
  backend/spring/src/main/java/com/tec/workflix/models/Usuario.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/models/UsuarioServicio.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/Apis.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/Environment.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/UsuarioServicioService.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/tarjetas/CatalogoActivity.java
  frontend/mobile/workflix/app/src/main/res/layout/activity_crear_perfil.xml
  frontend/mobile/workflix/app/src/main/res/values/strings.xml
Labels: enhancement

#230 Pagina sucess stripe
  frontend/web/3.0.00/server_pasarela/public/logo_workflix.png
  frontend/web/3.0.00/server_pasarela/public/style.css
  frontend/web/3.0.00/server_pasarela/public/success.html
Labels: enhancement

#231 Web linking
  frontend/web/3.0.00/src/app/envs/environment.ts
  frontend/web/3.0.00/src/app/models/userService.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/services/user-service.service.spec.ts
  frontend/web/3.0.00/src/app/services/user-service.service.ts
  frontend/web/3.0.00/src/app/services/user.service.ts
Labels: enhancement

#232 style correction chexbox registration
  frontend/web/3.0.00/server_pasarela/public/return.html
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.css
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.html
Labels: enhancement

#233 Users clean
  frontend/web/3.0.00/src/app/pages/destacados/destacados.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: bug

#234 Highlights
  frontend/web/3.0.00/src/app/pages/destacados/destacados.component.ts
Labels: bug

#238 [FIX] validation value length of cart
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
  frontend/web/3.0.00/src/app/services/carrito.service.ts
Labels: bug

#241 Fix filtro servicios
  frontend/web/3.0.00/src/app/models/user.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: bug, enhancement

#242 Boton contratar carrito
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.css
  frontend/web/3.0.00/src/app/components/carrito/carrito.component.html
Labels: enhancement

#244 Clean code
  frontend/web/3.0.00/src/app/envs/environment.ts
  frontend/web/3.0.00/src/app/pages/dashboard/user-create/user-create.component.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.ts
  frontend/web/3.0.00/src/app/pages/registrarse/registrarse.component.ts
  frontend/web/3.0.00/src/app/services/login.service.ts
  frontend/web/3.0.00/src/app/services/register.service.ts
  frontend/web/3.0.00/src/app/services/service.service.ts
  frontend/web/3.0.00/src/app/services/user.service.ts
Labels: enhancement

#246 [ADD] cancel.html
  frontend/web/3.0.00/server_pasarela/public/cancel.html
Labels: enhancement

#247 Add images
  backend/spring/pom.xml
  backend/spring/src/main/java/com/tec/workflix/configuration/FileUploadConfig.java
  backend/spring/src/main/java/com/tec/workflix/controllers/UsuarioController.java
  backend/spring/src/main/java/com/tec/workflix/services/UsuarioService.java
  backend/spring/src/main/resources/static/images/gatito.jpg
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: enhancement

#248 All images cards
  backend/spring/src/main/resources/static/images/hombre_1.jpg
  backend/spring/src/main/resources/static/images/hombre_2.jpeg
  backend/spring/src/main/resources/static/images/hombre_3.webp
  backend/spring/src/main/resources/static/images/hombre_4.webp
  backend/spring/src/main/resources/static/images/hombre_5.jpeg
  backend/spring/src/main/resources/static/images/hombre_6.jpg
  backend/spring/src/main/resources/static/images/hombre_7.jpg
  backend/spring/src/main/resources/static/images/hombre_8.jpg
  backend/spring/src/main/resources/static/images/hombre_9.webp
  backend/spring/src/main/resources/static/images/mujer_1.jpeg
  backend/spring/src/main/resources/static/images/mujer_2.jpg
  backend/spring/src/main/resources/static/images/mujer_3.jpeg
  backend/spring/src/main/resources/static/images/mujer_4.webp
  backend/spring/src/main/resources/static/images/mujer_5.webp
  backend/spring/src/main/resources/static/images/mujer_6.webp
  backend/spring/src/main/resources/static/images/mujer_7.jpeg
  backend/spring/src/main/resources/static/images/mujer_8.webp
  backend/spring/src/main/resources/static/images/mujer_9.webp
  backend/spring/src/main/resources/static/images/sin_foto.webp
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: enhancement

#249 Images section
  frontend/web/3.0.00/src/app/pages/destacados/destacados.component.html
  frontend/web/3.0.00/src/app/pages/destacados/destacados.component.ts
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.html
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.html
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.html
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
  frontend/web/3.0.00/src/assets/images/sin_foto.webp
Labels: enhancement

#251 Fix profile image
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/perfil_terminos/PerfilTerminosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/tarjetas/TarjetaAmpliadaActivity.java
  frontend/mobile/workflix/app/src/main/res/layout/activity_crear_perfil.xml
Labels: enhancement

#253 Chat bot
  backend/spring/src/main/resources/db_script/main.sql
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/chat/chat.component.css
  frontend/web/3.0.00/src/app/pages/chat/chat.component.html
  frontend/web/3.0.00/src/app/pages/chat/chat.component.spec.ts
  frontend/web/3.0.00/src/app/pages/chat/chat.component.ts
  frontend/web/3.0.00/src/app/services/chat.service.spec.ts
  frontend/web/3.0.00/src/app/services/chat.service.ts
Labels: bug

#255 254 tk219 create boot chat questions and answers
  frontend/web/3.0.00/src/app/pages/chat/chat.component.css
  frontend/web/3.0.00/src/app/pages/chat/chat.component.html
  frontend/web/3.0.00/src/app/pages/chat/chat.component.ts
  frontend/web/3.0.00/src/app/services/chat.service.ts
Labels: enhancement
