Repository workflix/workflix-full, pull requests merged in 2024-04, with the labels that each got.

#37 agrega logo workflix
  documentos/login_banner.jpg
Labels: documentation

#39 [ADD] conexion a backend spring
  backend/spring/src/main/java/com/tec/workflix/controllers/UsuarioController.java
  frontend/web/.angular/cache/15.2.8/angular-webpack/bc3e5d9e3d7fd21ba287316cac0db8219c964cea/0.pack
  frontend/web/.angular/cache/15.2.8/angular-webpack/bc3e5d9e3d7fd21ba287316cac0db8219c964cea/1.pack
  frontend/web/.angular/cache/15.2.8/angular-webpack/bc3e5d9e3d7fd21ba287316cac0db8219c964cea/index.pack
  frontend/web/src/app/layouts/pages/cards/cards.component.css
  frontend/web/src/app/layouts/pages/cards/cards.component.html
  frontend/web/src/app/layouts/pages/cards/cards.component.spec.ts
  frontend/web/src/app/layouts/pages/cards/cards.component.ts
  frontend/web/src/app/layouts/pages/home/home.component.html
  frontend/web/src/app/layouts/pages/home/home.component.ts
  frontend/web/src/app/layouts/pages/pages.module.ts
  frontend/web/src/app/modelos/user.spec.ts
  frontend/web/src/app/modelos/user.ts
  frontend/web/src/app/servicios/user.service.ts
  frontend/web/src/app/servicios/usuarios.service.ts
  frontend/web/src/assets/images/foto_hombre.jpg
  frontend/web/src/assets/images/foto_hombre_2.jpg
  frontend/web/src/assets/images/foto_mujer.jpg
  frontend/web/src/assets/images/foto_mujer_2.jpeg
  frontend/web/src/assets/images/no_img.jpg
  frontend/web/src/environments/environment.ts
Labels: enhancement

#42 se agrega leyenda de olvido de contraseña en login
  frontend/web/src/app/pages/login/login.component.html
Labels: good first issue

#47 [ADD] Mapa del Sitio
  documentos/workflix-mapa-del-sitio.png
Labels: documentation

#48 Estilos tarjetas
  frontend/web/src/app/pages/cards/cards.component.css
  frontend/web/src/app/pages/cards/cards.component.html
  frontend/web/src/app/pages/cards/cards.component.ts
  frontend/web/src/app/pages/home/home.component.html
Labels: enhancement

#66 Login back
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/guards/auth.guard.ts
  frontend/web/3.0.00/src/app/services/login.service.ts
Labels: enhancement

#67 Ingresar page
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.css
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.html
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.spec.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.ts
  frontend/web/3.0.00/src/app/pages/login/archivo_vacio.txt
Labels: Migration

#68 Register back
  frontend/web/3.0.00/src/app/services/register.service.spec.ts
  frontend/web/3.0.00/src/app/services/register.service.ts
Labels: enhancement
