Repository workflix/workflix-full, pull requests merged in 2024-06, with the labels that each got.

#256 Profile prof
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.html
  frontend/web/3.0.00/src/app/pages/detalle-tarjeta/detalle-tarjeta.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-profesional/perfil-profesional.component.ts
  frontend/web/3.0.00/src/app/pages/perfil-usuario/perfil-usuario.component.ts
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.html
  frontend/web/3.0.00/src/app/pages/tarjetas/tarjetas.component.ts
Labels: bug

#257 Update profile
  backend/spring/src/main/java/com/tec/workflix/models/Usuario.java
  backend/spring/src/main/java/com/tec/workflix/modelsDAO/UsuarioDAO.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/models/Usuario.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/UsuarioService.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/auth/login/LoginActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardAdminVistaActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/dashboard/DashboardUsuariosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/Perfil.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/perfil/perfil_terminos/PerfilTerminosActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/tarjetas/CatalogoActivity.java
  frontend/mobile/workflix/app/src/main/res/layout/activity_crear_perfil.xml
  frontend/mobile/workflix/app/src/main/res/layout/activity_perfil_terminos.xml
Labels: bug

#260 Dashboard mobile
  backend/spring/src/main/java/com/tec/workflix/models/UsuarioServicio.java
  backend/spring/src/main/java/com/tec/workflix/modelsDAO/UsuarioDAO.java
  backend/spring/src/main/resources/db_script/main.sql
  backend/spring/src/main/resources/static/images/admin.png
Labels: bug

#262 Dashboard services
  backend/spring/src/main/java/com/tec/workflix/modelsDAO/ServicioDAO.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/ServicioService.java
Labels: bug

#263 [ADD] questions and answers to chatbot
  frontend/web/3.0.00/src/app/services/chat.service.ts
Labels: enhancement

#264 Chat bot mobile
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/Environment.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/utils/OnBackPressedListener.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/MainActivity.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/HomeFragment.java
  frontend/mobile/workflix/app/src/main/res/layout/fragment_home.xml
  frontend/web/3.0.00/README.md
Labels: bug

#265 Add the functionality to retrieve password via email
  backend/spring/pom.xml
  backend/spring/src/main/java/com/tec/workflix/configuration/ThymeleafTemplateConfig.java
  backend/spring/src/main/java/com/tec/workflix/controllers/EmailController.java
  backend/spring/src/main/java/com/tec/workflix/controllers/UsuarioController.java
  backend/spring/src/main/java/com/tec/workflix/models/Clave.java
  backend/spring/src/main/java/com/tec/workflix/models/Email.java
  backend/spring/src/main/java/com/tec/workflix/models/Usuario.java
  backend/spring/src/main/java/com/tec/workflix/repository/IUsuarioRepository.java
  backend/spring/src/main/java/com/tec/workflix/services/EmailService.java
  backend/spring/src/main/java/com/tec/workflix/services/UsuarioService.java
  backend/spring/src/main/resources/Templates/email-template.html
  backend/spring/src/main/resources/application.properties
  frontend/web/3.0.00/src/app/app.routes.ts
  frontend/web/3.0.00/src/app/envs/environment.ts
  frontend/web/3.0.00/src/app/models/email.ts
  frontend/web/3.0.00/src/app/models/password.ts
  frontend/web/3.0.00/src/app/pages/recuperar-clave/cambiar-clave.component.css
  frontend/web/3.0.00/src/app/pages/recuperar-clave/cambiar-clave.component.html
  frontend/web/3.0.00/src/app/pages/recuperar-clave/cambiar-clave.component.spec.ts
  frontend/web/3.0.00/src/app/pages/recuperar-clave/cambiar-clave.component.ts
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.css
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.html
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.ts
  frontend/web/3.0.00/src/app/services/email-password.service.spec.ts
  frontend/web/3.0.00/src/app/services/email-password.service.ts
Labels: enhancement

#267 [DEL] invalid documentation and [ADD] new IEEE documentation
  documents/IEEE830 Workflix-2024.pdf
Labels: documentation

#271 [UPDATE] front-end
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/ContactMail.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/restablecer/RestablecerActivity.java
  frontend/mobile/workflix/app/src/main/res/layout/activity_restablecer.xml
  frontend/mobile/workflix/app/src/main/res/layout/fragment_contact_mail.xml
Labels: enhancement

#272 Merge dev to main
  README.md
  backend/spring/src/main/resources/Templates/email-template.html
  backend/spring/src/main/resources/application.properties
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/menu/ContactMail.java
  frontend/mobile/workflix/app/src/main/java/tec/ispc/workflix/views/ui/restablecer/RestablecerActivity.java
  frontend/mobile/workflix/app/src/main/res/layout/activity_restablecer.xml
  frontend/mobile/workflix/app/src/main/res/layout/fragment_contact_mail.xml
  frontend/web/3.0.00/src/app/models/user.ts
  frontend/web/3.0.00/src/app/pages/ingresar/ingresar.component.html
  frontend/web/3.0.00/src/app/pages/page-not-found/page-not-found.component.html
  frontend/web/3.0.00/src/app/pages/recuperar-clave/cambiar-clave.component.css
  frontend/web/3.0.00/src/app/pages/recuperar-clave/cambiar-clave.component.html
  frontend/web/3.0.00/src/app/pages/recuperar-clave/cambiar-clave.component.ts
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.css
  frontend/web/3.0.00/src/app/pages/recuperar-clave/recuperar-clave.component.html
Labels: bug, enhancement
